[project]
name = "agentity"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "langchain>=1.2",
    "langchain-openai>=1.1",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = ["ruff", "ty"]

[tool.ruff]
line-length = 120
